export const defaultSettings = [
    { value: 'IP', selected: true, pos: 'p' },
    { value: 'W', selected: false, pos: 'p' },
    { value: 'L', selected: false, pos: 'p' },
    { value: 'ERA', selected: false, pos: 'p' },
    { value: 'WHIP', selected: false, pos: 'p' },
    { value: 'FIP', selected: true, pos: 'p' },
    { value: 'xFIP', selected: false, pos: 'p' },
    { value: 'K/9', selected: false, pos: 'p' },
    { value: 'BB/9', selected: false, pos: 'p' },
    { value: 'K/BB', selected: false, pos: 'p' },
    { value: 'H/9', selected: false, pos: 'p' },
    { value: 'GB%', selected: false, pos: 'p' },
    { value: 'SwStr%', selected: false, pos: 'p' },
    { value: 'K%', selected: false, pos: 'p' },
    { value: 'WAR', selected: true, pos: 'p' },

    { value: 'G', selected: true, pos: 'b' },
    { value: 'PA', selected: true, pos: 'b' },
    { value: 'AB', selected: false, pos: 'b' },
    { value: '1B', selected: false, pos: 'b' },
    { value: '2B', selected: false, pos: 'b' },
    { value: '3B', selected: false, pos: 'b' },
    { value: 'HR', selected: true, pos: 'b' },
    { value: 'RBI', selected: false, pos: 'b' },
    { value: 'BB', selected: false, pos: 'b' },
    { value: 'SO', selected: false, pos: 'b' },
    { value: 'AVG', selected: false, pos: 'b' },
    { value: 'OBP', selected: false, pos: 'b' },
    { value: 'SLG', selected: false, pos: 'b' },
    { value: 'OPS', selected: false, pos: 'b' },
    { value: 'BABIP', selected: false, pos: 'b' },
    { value: 'wOBA', selected: false, pos: 'b' },
    { value: 'wRC+', selected: true, pos: 'b' },
    { value: 'WAR', selected: true, pos: 'b' },
];
